name: GitHub Actions-Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Start an ML compute cluster
      run: az ml compute start --name compute-sh-dl --resource-group sh-machinelearn
                    --workspace-name sh-machinelearn-ws --no-wait
    - name: Trigger Azure Machine Learning train job
      run: az ml job create --file src/job.yml --resource-group sh-machinelearn
                    --workspace-name sh-machinelearn-ws

